theme: jekyll-theme-midnight
title: Online Experiments for Language Scientists
description: Academic year 2025-2026
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.md
